name: "Deploy Networking resources"

on:
    pull_request:
        branches:
             - main
             - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}


jobs:
    validation:
        name: "Validation Job"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/checkout@v2

            - name: Python Setup
              uses: actions/setup-python@v2

            - name: Run Python Helper Script
              run: |
                cd script
                python3 replace_tf_values.py

            - name: Upload Updated Terraform Files
              uses: actions/upload-artifact@v3
              with:
                name: updated-terraform-files
                path: iac/

            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v2

            - name: Validate Terraform
              run: |
                cd iac
                terraform init
                terraform validate


    deployment:
        name: "Deployment Job"
        needs: validation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Download Updated Terraform Files
              uses: actions/download-artifact@v3
              with:
                name: updated-terraform-files
                path: iac 
            
            - name: Terraform Setup
              uses: hashicorp/setup-terraform@v2

            - name: Apply Terraform Resources
              run: |
                cd iac
                terraform init 
                terraform destroy -auto-approve 

              